### ISSUE TITLE
Certs uploaded through the Config app break the Quay pod.

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#178]
**Description:**

If a User uploads a self-signed certificate to communicate with external services (e.g. LDAP) using the Quay Configuration application, then the Quay pods will fail on initilization.

The error indicates this is related to the mounted secret at `/conf/stack` being read-only, which is expected behavior when using a secret. However, this has worked in the past without the operator.

Here is an important portion of the logs as shared by Quay's QE:
```
Running all default registry services
Running init script '/quay-registry/conf/init/02_get_kube_certs.sh'
Running on kubernetes, attempting to retrieve extra certs from secret
Found an extra cert %s in config-secret, copying to kube ca dir
Traceback (most recent call last):
File "/quay-registry/conf/init/02_get_kube_certs.py", line 81, in <module>
main()
File "/quay-registry/conf/init/02_get_kube_certs.py", line 76, in main
with open(os.path.join(KUBE_EXTRA_CA_CERTDIR, cert_filename), "w") as f:
IOError: [Errno 30] Read-only file system: u'/conf/stack/extra_ca_certs/noobaas3.crt'
```

This is a reference to the associated file which attempts to fetch the "missing" certificate and store it locally: https://github.com/quay/quay/blob/master/conf/init/02_get_kube_certs.py

I believe the issue is related to the way the secret is mounted. Quay finds a certificate in its secret but does not see it locally, so it tries to write it locally.

**Steps to Reproduce**

1. Deploy Quay Ecosystem. Configure CR to *not* stop the Configuration Application.
2. Access the Configuration Application.
3. Use the "Upload Certifiates" to upload any valid certificate with the name `foo.crt`.
4. Save the configuration.
5. The file `foo.crt` should now exist in Quay's configuration secret.
6. Restart the Quay Pod(s)
7. They should fail with the error mentioned above.

**Acceptance Criteria**

Users should be able to upload certificates through the Quay Config application and any Quay pods should be able to use those certificates successfully.

**Comment by kurtismullins** [comment]
Comment redacted. It was referencing a different Issue.
