### ISSUE TITLE
Quay pod does not start up with missing config secret error

### ISSUE THREAD

**Issue by wkulhanek** [quay/quay-operator#28]
When deploying a Quay the other pods come up. But the quay pod itself does not come up.

Logs:

   __   __
  /  \ /  \     ______   _    _     __   __   __
 / /\ / /\ \   /  __  \ | |  | |   /  \  \ \ / /
/ /  / /  \ \  | |  | | | |  | |  / /\ \  \   /
\ \  \ \  / /  | |__| | | |__| | / ____ \  | |
 \ \/ \ \/ /   \_  ___/  \____/ /_/    \_\ |_|
  \__/ \__/      \ \__
                  \___\ by Red Hat

 Build, Store, and Distribute your Containers

Running both interactive and batch scripts
Running init script '/quay-registry/conf/init/01_copy_syslog_config.sh'
Running init script '/quay-registry/conf/init/02_get_kube_certs.sh'
Running on kubernetes, attempting to retrieve extra certs from secret
/opt/rh/python27/root/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/quay-registry/conf/init/02_get_kube_certs.py", line 71, in <module>
    main()
  File "/quay-registry/conf/init/02_get_kube_certs.py", line 55, in main
    secret_data = _lookup_secret(service_token).get('data', {})
  File "/quay-registry/conf/init/02_get_kube_certs.py", line 26, in _lookup_secret
    raise Exception('Cannot get the config secret')
Exception: Cannot get the config secret

**Comment by wkulhanek** [comment]
@sabre1041 This turns out to be a hardcoded quay-enterprise namespace. We need a way to customize the namespace that quay is deployed (e.g. quay-aaaa, quay-bbbb, ....) for multiple Quay Deployments on one OCP Cluster.

**Comment by wkulhanek** [comment]
Fixed.
